
services:
  backend:
    build: ./backend
    container_name: casa-backend
    ports:
      - "5001:5000"
    environment:
      DB_HOST: db
      DB_NAME: casaBite
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_PORT: 5432
      JWT_SECRET: siham1234
      JWT_EXPIRES: 7d
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm start

  db:
    image: postgres:15
    container_name: casaBite
    environment:
      POSTGRES_DB: casaBite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: